[package]
name = "walnut-dns"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
arc-swap = "1"
camino = "1"
chrono = "0.4"
clap = { version = "4", optional = true }
data-encoding = { version = "2.2.0", default-features = false }
hickory-proto = { version = "0.25", features = ["mdns", "dnssec-ring"] }
hickory-server = { version = "0.25", features = ["dnssec-ring"] }
rusqlite = { version = "0.37", features = ["blob", "chrono", "uuid", "trace"] }
rustls-pki-types = "1.10"
rustls = { version = "0.23", default-features = false, features = ["logging", "std", "tls12"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net"], optional = true }
zeroize = "1"

[dependencies.uuid]
version = "^1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]

[dependencies.monarch-db]
version = "0.1"
# git = "https://github.com/alexrudy/monarch-db.git"

[dependencies.tracing-subscriber]
version = "^0.3"
features = ["env-filter", "json", "fmt", "ansi", "std"]
optional = true

[dev-dependencies]
futures = "0.3"
hickory-client = { version = "0.25" }
hickory-proto = { version = "0.25", features = ["tls-ring"] }
hickory-server = { version = "0.25", features = ["testing", "tls-ring"] }
serde_json = "1.0"
tempfile = "3.0"
tokio = "1"
tower = "0.5"

[dev-dependencies.tracing-subscriber]
version = "^0.3"
features = ["env-filter", "json", "fmt", "ansi", "std"]

[features]
default = []
bundled = ["rusqlite/bundled"]
cli = ["dep:clap", "dep:tokio", "dep:tracing-subscriber"]

[[bin]]
name = "walnut-dns"
path = "src/bin/manage.rs"
required-features = ["cli"]
